# -------------------------
# OpenOCR 기본 환경 설정
# -------------------------

APP_NAME: OpenOCR-basaaja                              # basaaja -> sungnambang notebook, dev -> 개발서버, prod -> 운영서버 

# 로그가 저장될 로컬 디렉터리 (존재해야 함)
LOG_DIR: ../openocr_log

# 다운로드한 임시 이미지 보관 위치
DOWNLOAD_IMAGE_DIR: ../ocr_image/temp/download_image

# 이미지를 다운로드하는 기간계 서버  ( 끝에 슬래시 / 필수 )
IMAGE_WEB_SERVER_DIR: "http://127.0.0.1:5002/image/"

# 최종 정보를 전송하는 API/GW 기간계 서버  ( 끝에 슬래시 / 필수 )
RESULT_WEB_SERVER_DIR: "http://127.0.0.1:5002/create/"

# MMS-MO가 FTP 를 통해서 저장되는 위치 
MMS_NAS_DIR: /Users/basaaja/Python/ocr_image/temp/mms_nas

# 검증 데이터 경로 ( 개발,운영에선 사용하지 않음 )
OCR_JSON_PATH: ./util/ju_data.json

# OCR 결과 이미지를 저장할 디렉터리
OCR_OUTPUT_DIR: /Users/basaaja/Python/ocr_image/temp/output_image

# OCR 문자 인식 결과 저장 디렉토리
OCR_CHAR_RESULT_DIR: ../ocr_image/temp/ocr_char_result


# 로그 레벨 (DEBUG / INFO / WARNING / ERROR / CRITICAL)
LOG_LEVEL: DEBUG

# OCR 모델 경로 설정 (추가된 부분)
CLS_MODEL_PATH: "./models/effb0_ga_ju.onnx"
CLS_INTRA_OP_NUM_THREADS: 4 # ONNX 탐지 모델 시 하나의 연산에 사용할  쓰레드 : 기본값 4개 ( CPU 수만큼 설정 필요 )
CLS_INTER_OP_NUM_THREADS: 1 # ONNX 탐지 모델 시 병렬 연산에 사용할  쓰레드 : 기본값 1개 ( 일반적으로 1개 설정  )

YOLOX_MODEL_PATH_GA: "./models/yolox_m_family_1024_ga.onnx"
YOLOX_MODEL_PATH_JU: "./models/yolox_m_family_1024.onnx"
YOLOX_MODEL_PATH_ROW: "./models/yolox_m_row.onnx"

# OCR 처리용 임시 입력 디렉토리 (main.py의 download_save_and_ocr_background 함수에서 사용)
# 이 설정은 이미 main.py 로직에 필요할 수 있으므로, 기존 설정에 따라 확인해주세요.
OCR_INPUT_DIR: "/Users/basaaja/Python/ocr_image/temp/ocr_input_temp" # 예시 경로

# EasyOCR Cache 디렉토리 경로
EASYOCR_STORAGE_DIR: "../ocr_image/temp/easyocr_storage"

# 허용할 이미지 확ㅏ자
VALID_IMAGE_EXTENSIONS:
  - .jpg
  - .jpeg
  - .png
  - .bmp
  - .webp
  - .tif

